backend:
  name: git-gateway
  branch: main

collections:
  - name: "reservas"
    label: "Reservas"
    folder: "content/reservas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Correo", name: "correo", widget: "string" }
      - { label: "Teléfono", name: "telefono", widget: "string" }